---
- name: Patching labels to {{ kind }} kind
  k8s:
    state: present
    definition:
      apiVersion: '{{ api_version }}'
      kind: '{{ kind }}'
      name: '{{ ansible_operator_meta.name }}'
      namespace: '{{ ansible_operator_meta.namespace }}'
      metadata:
        name: '{{ ansible_operator_meta.name }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
          awx/name: '{{ ansible_operator_meta.name }}'
          awx/part-of: '{{ ansible_operator_meta.name }}'
          awx/managed-by: '{{ deployment_type }}-operator'
          awx/component: '{{ deployment_type }}'
          awx/operator-version: '{{ lookup("env", "OPERATOR_VERSION") }}'

- name: Look up details for this restore object
  k8s_info:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: this_restore

- block:
    - include_tasks: init.yml

    - include_tasks: secrets.yml

    - include_tasks: deploy_awx.yml

    - include_tasks: postgres.yml

    - name: Set flag signifying this restore was successful
      set_fact:
        tower_restore_complete: True

    - include_tasks: cleanup.yml

  when:
    - this_restore['resources'][0]['status']['restoreComplete'] is not defined

- name: Update status variables
  include_tasks: update_status.yml
